LABEL maintainer="Christoph Schranz <christoph.schranz@salzburgresearch.at>"

# Install latest Lightning and PyTorch
RUN pip install --no-cache-dir pytorch-lightning torch torchvision keras --upgrade

# Install PyTorch with dependencies
RUN conda install --quiet --yes \
    pyyaml mkl mkl-include setuptools cmake cffi typing

# Clean installation
RUN conda clean --all -f -y && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER
